INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('CHEVROLET',1,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('VOLKSWAGEN',2,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('FIAT',3,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MERCEDES-BENZ',4,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('CHANA',6,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('FORD',13,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HYUNDAI',14,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('KIA',16,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('TOYOTA',23,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('RENAULT',24,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('AGRALE',27,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('VOLVO',53,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ISUZU',84,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('IVECO',85,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('UTILITARIOS AGRICOLAS',131,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('TRAILER',164,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('RANDON',167,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SCANIA',242,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('OUTROS (',261,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ONIBUS (',263,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('UTILITARIOS PESADOS',266,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MOTOR-HOME',270,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MAN',274,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('NAVISTAR',275,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SINOTRUK',277,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SCHIFFER',284,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('GUERRA',285,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MICHIGAN',292,NULL,1);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('CHEVROLET',1,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('VOLKSWAGEN',2,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('FIAT',3,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MERCEDES-BENZ',4,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('CITROEN',5,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('CHANA',6,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HONDA',7,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SUBARU',8,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('FERRARI',10,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BUGATTI',11,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LAMBORGHINI',12,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('FORD',13,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HYUNDAI',14,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('JAC',15,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('KIA',16,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('GURGEL',17,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DODGE',18,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('CHRYSLER',19,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BENTLEY',20,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SSANGYONG',21,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('PEUGEOT',22,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('TOYOTA',23,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('RENAULT',24,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ACURA',25,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ADAMO',26,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('AGRALE',27,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ALFA ROMEO',28,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('AMERICAR',29,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ASTON MARTIN',31,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('AUDI',32,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BEACH',34,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BIANCO',35,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BMW',36,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BORGWARD',37,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BRILLIANCE',38,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BUICK',41,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('CBT',42,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('NISSAN',43,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('CHAMONIX',44,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('CHEDA',46,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('CHERY',47,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('CORD',48,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('COYOTE',49,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('CROSS LANDER',50,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DAEWOO',51,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DAIHATSU',52,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('VOLVO',53,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DE SOTO',54,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DETOMAZO',55,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DELOREAN',56,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DKW-VEMAG',57,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SUZUKI',59,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('EAGLE',60,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('EFFA',61,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ENGESA',63,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ENVEMO',64,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('FARUS (',65,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('FERCAR',66,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('FNM',68,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('PONTIAC',69,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('PORSCHE',70,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('GEO',72,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('GRANCAR',74,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('GREAT WALL',75,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HAFEI',76,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HOFSTETTER',78,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HUDSON',79,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HUMMER',80,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('INFINITI',82,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('INTERNATIONAL',83,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('JAGUAR',86,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('JEEP',87,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('JINBEI',88,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('JPX',89,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('KAISER',90,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('KOENIGSEGG',91,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LAUTOMOBILE',92,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LAUTOCRAFT',93,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LADA',94,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LANCIA',95,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LAND ROVER',96,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LEXUS (',97,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LIFAN',98,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LINCOLN',99,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LOBINI',100,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LOTUS (',101,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MAHINDRA',102,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MASERATI',104,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MATRA',106,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MAYBACH',107,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MAZDA',108,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MENON',109,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MERCURY',110,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MITSUBISHI',111,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MG',112,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MINI',113,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MIURA',114,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MORRIS (',115,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MP LAFER',116,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MPLM',117,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('NEWTRACK',118,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('NISSIN',119,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('OLDSMOBILE',120,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('PAG',121,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('PAGANI',122,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('PLYMOUTH',123,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('PUMA',124,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('RENO',125,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('REVA-I',126,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ROLLS-ROYCE',127,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ROMI',129,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SEAT',130,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('UTILITARIOS AGRICOLAS (',131,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SHINERAY',132,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SAAB',137,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SHORT',139,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SIMCA',141,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SMART',142,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SPYKER',143,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('STANDARD',144,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('STUDEBAKER',145,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('TAC',146,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('TANGER',147,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('TRIUMPH',148,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('TROLLER',149,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('UNIMOG',150,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('WIESMANN',154,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('CADILLAC',155,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('AM GEN',156,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BUGGY',157,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('WILLYS OVERLAND',158,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('KASEA',161,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SATURN',162,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SWELL MINI',163,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SKODA',175,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('KARMANN GHIA',239,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('KART',254,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HANOMAG',258,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('OUTROS (',261,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HILLMAN',265,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HRG',288,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('GAIOLA',295,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('TATA',338,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DITALLY',341,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('RELY',345,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MCLAREN',346,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('GEELY',534,NULL,2);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HONDA',7,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('AGRALE',27,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BMW',36,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SUZUKI',59,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LIFAN',98,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MAHINDRA',102,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SHINERAY',132,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('KASINSKI',133,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('YAMAHA',135,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('GARINNI',136,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SUNDOWN',140,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('KAWASAKI',170,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('POLARIS (',171,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ADLY',176,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('AMAZONAS (',177,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('APRILIA',178,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ATALA',179,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BAJAJ',180,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BENELLI',181,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BETA',182,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BIMOTA',183,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BRANDY',184,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BRAVA',185,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BRP',186,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BUELL',187,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BUENO',188,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('CAGIVA',190,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MOBILETE',191,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DAELIM',192,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DAFRA',193,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DAYANG',194,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DAYUN',195,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DERBI',196,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DUCATI',197,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('EMME',198,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('FYM',200,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('GAS GAS (',201,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('GREEN',202,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HAOBAO',203,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HARLEY-DAVIDSON',204,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HARTFORD',205,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HERO',206,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HUSABERG',207,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('HUSQVARNA',208,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('IROS (',209,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('JIAPENG VOLCANO',210,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('JOHNNYPAG',211,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('JONNY',212,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('KAHENA',213,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('KIMCO',214,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LAQUILA',215,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LANDUM',216,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LAVRALE',217,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LERIVO',218,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LON-V',219,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('TRICICLO',220,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MALAGUTI',221,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MIZA',222,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MOTO GUZZI',223,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MRX',224,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MV AUGUSTA',225,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MVK',226,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ORCA',227,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('PEGASSI',228,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('PIAGGIO',229,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('REGAL RAPTOR',230,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SANYANG',231,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SIAMOTO',232,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('TARGOS (',233,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('TRAXX',234,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('VENTO',235,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('WUYANG',236,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('GARRA',245,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('X MOTOS (',246,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('TRICKER',248,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LAMBRETA',253,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('OUTROS (',261,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('SCOOTER',269,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ZONGSHEN',281,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BIRELLI',282,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('WALK MACHINE',294,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('FBM',297,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ARIEL',299,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DUCAR',340,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('DITALLY',341,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('MARVA',342,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('WOLVER',343,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('KTM',344,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('LEOPARD',347,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('JAWA',348,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BULL',349,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('CAN-AM',358,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('ACELLERA',359,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('VICTORY',483,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('INDIAN',484,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('BRAVAX',532,NULL,3);
INSERT INTO marcas (mar_nome,mar_cod,mar_icone,cat_id) VALUES ('GARELLI',533,NULL,3);