INSERT INTO `categorias_servicos` (`cat_serv_id`,`cat_serv_nome`) VALUES (1,'Lavagem e Higienizacao');
INSERT INTO `categorias_servicos` (`cat_serv_id`,`cat_serv_nome`) VALUES (2,'Polimento e Protecao da Pintura');
INSERT INTO `categorias_servicos` (`cat_serv_id`,`cat_serv_nome`) VALUES (3,'Cuidados com Vidros e Farois');
INSERT INTO `categorias_servicos` (`cat_serv_id`,`cat_serv_nome`) VALUES (4,'Cuidados com Rodas e Pneus');
INSERT INTO `categorias_servicos` (`cat_serv_id`,`cat_serv_nome`) VALUES (5,'Detalhamento Interno (tailing)');
INSERT INTO `categorias_servicos` (`cat_serv_id`,`cat_serv_nome`) VALUES (6,'Remocao de Odores');
INSERT INTO `categorias_servicos` (`cat_serv_id`,`cat_serv_nome`) VALUES (7,'Correcao de Pintura');
INSERT INTO `categorias_servicos` (`cat_serv_id`,`cat_serv_nome`) VALUES (8,'Customizacao');
INSERT INTO `categorias_servicos` (`cat_serv_id`,`cat_serv_nome`) VALUES (9,'Reparos Esteticos');
INSERT INTO `categorias_servicos` (`cat_serv_id`,`cat_serv_nome`) VALUES (10,'Servicos Adicionais');
